import test from 'node:test';
import assert from 'node:assert/strict';
import { buildSharePayload, importCommunityCsv } from '../public/community-share.js';

test('share payload excludes screenshot data and preserves method, date and floor', () => {
  const find = { id: 'f', name: 'Seeker Grenade', map: 'Stella Montis Upper', x: .23, y: .13,
    foundAt: '2026-09-29T17:49:31Z', autoGenerated: true, nameSource: 'catalog icon', sightingId: 's', frame: 'private screenshot' };
  const payload = buildSharePayload('ZHomeSlice', [find], [{ id: 's', iconConfidence: .9, confidence: .96, tilePreview: 'private tile' }]);
  assert.equal(payload.finds[0].method, 'automatic');
  assert.equal(payload.finds[0].map, 'Stella Montis Upper');
  assert.equal(payload.finds[0].foundAt, '2026-09-29T17:49:31.000Z');
  assert.ok(payload.finds[0].score > 75);
  assert.equal(JSON.stringify(payload).includes('private'), false);
});

test('CSV import handles quoted JSON and keeps the latest valid response per player', () => {
  const make = (name, blueprint) => JSON.stringify({ version: 1, gameName: name, finds: [{ name: blueprint,
    map: 'Stella Montis Lower', x: .2, y: .4, foundAt: '2026-09-29T17:49:31Z', method: 'manual', score: 78 }] });
  const field = value => `"${value.replaceAll('"', '""')}"`;
  const csv = `Timestamp,Game name,Blueprint JSON\n1,ZHomeSlice,${field(make('ZHomeSlice', 'Old'))}\n` +
    `2,ZHomeSlice,${field(make('ZHomeSlice', 'New'))}\n3,ZHomeSlice,invalid\n`;
  const result = importCommunityCsv(csv);
  assert.equal(result.players.length, 1);
  assert.equal(result.players[0].finds[0].name, 'New');
  assert.equal(result.rejected, 1);
});

test('community sharing and import exclude custom maps and pixel-coordinate finds', () => {
  const good = { id: 'f', name: 'Defibrillator', map: 'Stella Montis Upper', x: .25, y: .5, foundAt: '2026-10-01T12:00:00Z' };
  const payload = buildSharePayload('Player', [good, { ...good, map: 'Custom map' }, { ...good, x: 250 }]);
  assert.equal(payload.finds.length, 1);
  const raw = JSON.stringify({ ...payload, finds: [...payload.finds, { ...good, map: 'Custom map' }, { ...good, x: 250 }] });
  const csv = `Game name,Blueprint JSON\nPlayer,"${raw.replaceAll('"', '""')}"\n`;
  assert.equal(importCommunityCsv(csv).players[0].finds.length, 1);
});
