import test from 'node:test';
import assert from 'node:assert/strict';
import { buildSharePayload, importCommunityCsv } from '../public/community-share.js';

test('share payload excludes screenshot data and preserves method, date and floor', () => {
  const find = { id: 'f', name: 'Seeker Grenade', map: 'Stella Montis Upper', x: .23, y: .13,
    foundAt: '2026-09-29T17:49:31Z', autoGenerated: true, nameSource: 'catalog icon', sightingId: 's', frame: 'private screenshot' };
  const payload = buildSharePayload('ZHomeSlice', [find], [{ id: 's', iconConfidence: .9, confidence: .96, tilePreview: 'private tile' }]);
  assert.equal(payload.finds[0].method, 'automatic');
  assert.equal(payload.finds[0].map, 'Stella Montis Upper');
  assert.equal(payload.finds[0].foundAt, '2026-09-29T17:49:31.000Z');
  assert.ok(payload.finds[0].score > 75);
  assert.equal(JSON.stringify(payload).includes('private'), false);
});

test('CSV import handles quoted JSON and keeps the latest valid response per player', () => {
  const make = (name, blueprint) => JSON.stringify({ version: 1, gameName: name, finds: [{ name: blueprint,
    map: 'Stella Montis Lower', x: .2, y: .4, foundAt: '2026-09-29T17:49:31Z', method: 'manual', score: 78 }] });
  const field = value => `"${value.replaceAll('"', '""')}"`;
  const csv = `Timestamp,Game name,Blueprint JSON\n1,ZHomeSlice,${field(make('ZHomeSlice', 'Old'))}\n` +
    `2,ZHomeSlice,${field(make('ZHomeSlice', 'New'))}\n3,ZHomeSlice,invalid\n`;
  const result = importCommunityCsv(csv);
  assert.equal(result.players.length, 1);
  assert.equal(result.players[0].finds[0].name, 'New');
  assert.equal(result.rejected, 1);
});
