import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { chromium } from 'file:///C:/Users/zhome/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';

const folder = 'C:/Program Files (x86)/Steam/userdata/297991134/760/remote/1808500/screenshots/';
const inventory = await readFile(folder + '20260928150336_1.jpg');
const map = await readFile(folder + '20260928150339_1.jpg');
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
try {
  const page = await browser.newPage();
  await page.route('**/test-deadline-inventory.jpg', route => route.fulfill({ status: 200, contentType: 'image/jpeg', body: inventory }));
  await page.route('**/test-deadline-map.jpg', route => route.fulfill({ status: 200, contentType: 'image/jpeg', body: map }));
  await page.route('**/vendor/tesseract.min.js', route => route.fulfill({ status: 200, contentType: 'text/javascript',
    body: 'window.Tesseract={createWorker:async()=>({recognize:async image=>image.width===960&&image.height===150?{data:{text:"STELLA MONTIS"}}:new Promise(()=>{})})};' }));
  await page.addInitScript(() => {
    navigator.mediaDevices.getDisplayMedia = async () => {
      const canvas = document.createElement('canvas'); canvas.width = 1600; canvas.height = 900;
      window.testSetFrame = async file => {
        const image = new Image(); image.src = file; await image.decode();
        canvas.getContext('2d').drawImage(image, 0, 0, 1600, 900);
      };
      await window.testSetFrame('/test-deadline-inventory.jpg');
      return canvas.captureStream(15);
    };
  });
  await page.goto('http://127.0.0.1:4177/');
  await page.locator('#preset-map').selectOption('stella-upper');
  await page.locator('#use-preset-map').click();
  await page.getByRole('button', { name: 'Start capture' }).click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('arc-blueprint-map-v1')).sightings[0]?.name === 'Deadline');
  await page.evaluate(() => window.testSetFrame('/test-deadline-map.jpg'));
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('arc-blueprint-map-v1')).finds.some(find => find.name === 'Deadline'));
  const result = await page.evaluate(() => {
    const saved = JSON.parse(localStorage.getItem('arc-blueprint-map-v1'));
    return { finds: saved.finds.map(find => ({ name: find.name, x: find.x, y: find.y, autoGenerated: find.autoGenerated })),
      sightings: saved.sightings.map(sighting => ({ name: sighting.name, savedFindId: sighting.savedFindId })),
      visiblePins: document.querySelectorAll('#pins .pin:not(.sighting-pin)').length };
  });
  assert.equal(result.finds.length, 1);
  assert.equal(result.finds[0].autoGenerated, true);
  assert.equal(result.sightings.length, 1);
  assert.ok(result.sightings[0].savedFindId);
  assert.ok(Math.abs(result.finds[0].x - 0.689656) < 0.01);
  assert.ok(Math.abs(result.finds[0].y - 0.322246) < 0.01);
  assert.equal(result.visiblePins, 1);
  console.log(JSON.stringify(result));
} finally { await browser.close(); }
