import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { chromium } from 'file:///C:/Users/zhome/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';

const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:4177/');
  await page.evaluate(async () => {
    const { emptyData } = await import('/backup.js');
    const data = emptyData(); data.currentMap = 'Stella Montis Upper';
    const canvas = document.createElement('canvas'); canvas.width = 105; canvas.height = 108;
    const ctx = canvas.getContext('2d'); ctx.fillStyle = '#163d8b'; ctx.fillRect(0, 0, 105, 108);
    ctx.fillStyle = '#eee'; ctx.fillRect(9, 84, 20, 14);
    const tilePreview = canvas.toDataURL();
    data.finds = [{ id: 'auto-find', name: 'Seeker Grenade', map: 'Stella Montis Lower', x: 0.28, y: 0.43,
      foundAt: '2026-10-01T12:00:00Z', autoGenerated: true, nameSource: 'OCR', sightingId: 'located' }];
    data.sightings = [
      { id: 'located', name: 'Seeker Grenade', map: 'Stella Montis Lower', position: { x: 0.28, y: 0.43 },
        seenAt: '2026-10-01T12:00:00Z', savedFindId: 'auto-find', tilePreview, frame: tilePreview },
      { id: 'unlocated', name: 'Unidentified blueprint', seenAt: '2026-10-01T12:10:00Z', tilePreview },
      { id: 'false-located', name: 'Deadline', dismissed: true, map: 'Stella Montis Lower',
        position: { x: 0.6, y: 0.6 }, seenAt: '2026-10-01T12:20:00Z', tilePreview, frame: tilePreview },
      { id: 'false-unlocated', name: 'Unknown item', dismissed: true, seenAt: '2026-10-01T12:30:00Z' },
    ];
    localStorage.setItem('arc-blueprint-map-v1', JSON.stringify(data));
  });
  await page.reload();
  const row = (list, name) => page.locator(`${list} .sighting-select`).filter({ hasText: name });
  assert.equal(await page.locator('#sighting-count').textContent(), '2');
  assert.equal(await page.locator('#sighting-list img.sighting-thumbnail').count(), 2);
  const size = await page.locator('#sighting-list .sighting-review').first().boundingBox();
  assert.equal(size.width, size.height, 'Review button is square');
  assert.equal(await page.locator('#sighting-list .sighting-review').first().getAttribute('aria-label'), 'Not a blueprint');

  await page.locator('#map-filters-toggle').click();
  await page.locator('#show-personal').uncheck();
  await page.locator('#map-filters-toggle').click();
  await row('#sighting-list', 'Seeker Grenade').click();
  await page.locator('#pin-popup-form').waitFor({ state: 'visible' });
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert.equal(await page.locator('#pin-popup-form').isVisible(), true, 'Editor survives destination map resize');
  assert.equal(await page.locator('#current-map-title').textContent(), 'Stella Montis Lower');
  assert.match(await page.locator('#map-content').getAttribute('style'), /scale\(2\.5\)/);
  assert.equal(await page.locator('[data-pin-id="auto-find"].selected-pin').count(), 1, 'Selected marker overrides visibility filters');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();

  await row('#sighting-list', 'Unidentified blueprint').click();
  assert.match(await page.locator('#map-content').getAttribute('style'), /scale\(1\)/);
  assert.equal(await page.locator('#pin-popup').isVisible(), false);
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('arc-blueprint-map-v1')).sightings.find(s => s.id === 'unlocated').position), undefined);
  await page.locator('#preset-map').selectOption('stella-upper');
  await page.locator('#use-preset-map').click();
  await page.locator('#map').click({ position: { x: 350, y: 370 } });
  await page.locator('#pin-popup-form').waitFor({ state: 'visible' });
  let saved = await page.evaluate(() => JSON.parse(localStorage.getItem('arc-blueprint-map-v1')));
  assert.equal(saved.sightings.find(s => s.id === 'unlocated').map, 'Stella Montis Upper');
  assert.ok(saved.sightings.find(s => s.id === 'unlocated').position);
  assert.equal(saved.sightings.find(s => s.id === 'unlocated').savedFindId, undefined);
  await page.getByRole('button', { name: 'Save changes' }).click();
  assert.equal(await page.locator('#pin-popup-form').isVisible(), true, 'Unknown item must choose a catalog blueprint');
  await page.locator('#pin-edit-blueprint-search').fill('Aphelion');
  await page.locator('#pin-edit-blueprint-list .blueprint-picker-option').click();
  await page.getByRole('button', { name: 'Save changes' }).click();
  assert.equal(await page.locator('#sighting-count').textContent(), '1');
  assert.equal(await row('#sighting-list', 'Aphelion').count(), 0, 'Completed item leaves review queue');
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('arc-blueprint-map-v1')));
  assert.equal(saved.sightings.find(s => s.id === 'unlocated').reviewVerdict, 'blueprint');
  assert.match(saved.finds.find(f => f.name === 'Aphelion').accuracy, /user selected/);

  await page.locator('#reviewed-sightings summary').click();
  await row('#reviewed-list', 'Deadline').click();
  await page.locator('#pin-popup-form').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#current-map-title').textContent(), 'Stella Montis Lower');
  assert.equal(await page.locator('[data-pin-id="false-located"].selected-pin').count(), 1);
  await page.locator('#sighting-review-note').fill('Actual blueprint, verified the book glyph.');
  await page.locator('#pin-edit-blueprint-search').fill('Deadline');
  await page.locator('#pin-edit-blueprint-list .blueprint-picker-option').click();
  await page.getByRole('button', { name: 'Save changes' }).click();
  assert.equal(await page.locator('#reviewed-count').textContent(), '1');
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('arc-blueprint-map-v1')));
  assert.equal(saved.sightings.find(s => s.id === 'false-located').dismissed, false);
  assert.equal(saved.dismissedTiles.some(s => s.id === 'false-located'), false);

  await row('#reviewed-list', 'Unknown item').click();
  assert.match(await page.locator('#map-content').getAttribute('style'), /scale\(1\)/);
  assert.equal(await page.locator('#pin-popup').isVisible(), false);
  await page.locator('#sighting-review-note').fill('Regular equipment; no blueprint book.');
  // Restore returns an unresolved item to the active queue without calling it a positive.
  await page.locator('#reviewed-list').getByRole('button', { name: 'Restore', exact: true }).click();
  assert.equal(await page.locator('#sighting-count').textContent(), '2');
  await row('#sighting-list', 'Unknown item').locator('..').getByRole('button', { name: 'Not a blueprint', exact: true }).click();
  await page.reload();
  assert.equal(await page.locator('#sighting-count').textContent(), '1');
  assert.equal(await page.locator('#reviewed-count').textContent(), '1');

  const downloadPromise = page.waitForEvent('download');
  await page.locator('#get-false-positive-feedback').click();
  const download = await downloadPromise;
  const bundle = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(bundle.examples.filter(e => e.verdict === 'blueprint').length, 2);
  assert.equal(bundle.examples.filter(e => e.verdict === 'not_blueprint').length, 1);
  assert.equal(bundle.examples.find(e => e.id === 'false-unlocated').notes, 'Regular equipment; no blueprint book.');
  const prompt = await page.evaluate(() => navigator.clipboard.readText());
  assert.ok(prompt.includes(download.suggestedFilename()));
  assert.match(await page.locator('#feedback-help').textContent(), /Prompt copied/);
  await page.evaluate(() => Object.defineProperty(navigator.clipboard, 'writeText', { value: async () => { throw new Error('Blocked'); } }));
  await page.locator('#get-false-positive-feedback').click();
  assert.equal(await page.locator('#feedback-prompt').isVisible(), true);
  await row('#sighting-list', 'Seeker Grenade').click();
  await page.locator('#pin-popup-form').waitFor({ state: 'visible' });
  await page.setViewportSize({ width: 1360, height: 1100 });
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert.equal(await page.locator('#pin-popup-form').isVisible(), true, 'Editor remains open after resizing');
  assert.match(await page.locator('#map-content').getAttribute('style'), /scale\(2\.5\)/);
  if (process.env.REVIEW_SCREENSHOT) {
    await page.locator('#map').screenshot({ path: process.env.REVIEW_SCREENSHOT });
    assert.equal(await page.locator('#pin-popup-form').isVisible(), true);
  }
  assert.deepEqual(errors, []);
  console.log('Sightings: captured thumbnails, square controls, map switching/highlight/zoom, manual placement, required catalog choice, queue resolution, false-alert correction, restore, labeled evidence download, clipboard and fallback passed.');
} finally { await browser.close(); }
